services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - '8000:8000'
    restart: "always"
